
classdef RBDLKinimaticsResponse < ros.Message
    %RBDLKinimaticsResponse MATLAB implementation of rbdl_server/RBDLKinimaticsResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLKinimaticsResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e65d9ceb74470ff27829ed47650deb13' % The MD5 Checksum of the message definition
        PropertyList = { 'Points' 'Names' } % List of non-constant message properties
        ROSPropertyList = { 'points' 'names' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Point' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Points
        Names
    end
    methods
        function set.Points(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.geometry_msgs.Point.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'RBDLKinimaticsResponse', 'Points')
            obj.Points = val;
        end
        function set.Names(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RBDLKinimaticsResponse', 'Names');
            obj.Names = cell(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLKinimaticsResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLKinimaticsResponse(strObj);
        end
    end
end
