
classdef RBDLInverseKinimaticsRequest < ros.Message
    %RBDLInverseKinimaticsRequest MATLAB implementation of rbdl_server/RBDLInverseKinimaticsRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLInverseKinimaticsRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '63ad227e0cf02f41a2dc7cb1e1426068' % The MD5 Checksum of the message definition
        PropertyList = { 'Target' 'ModelName' 'BodyName' } % List of non-constant message properties
        ROSPropertyList = { 'target' 'model_name' 'body_name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Point' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Target
        ModelName
        BodyName
    end
    methods
        function set.Target(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'RBDLInverseKinimaticsRequest', 'Target')
            obj.Target = val;
        end
        function set.ModelName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RBDLInverseKinimaticsRequest', 'ModelName');
            obj.ModelName = char(val);
        end
        function set.BodyName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RBDLInverseKinimaticsRequest', 'BodyName');
            obj.BodyName = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLInverseKinimaticsRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLInverseKinimaticsRequest(strObj);
        end
    end
end
