
classdef RBDLInverseDynamicsResponse < ros.Message
    %RBDLInverseDynamicsResponse MATLAB implementation of rbdl_server/RBDLInverseDynamicsResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLInverseDynamicsResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6488f72361a7c3710faf21208a8c781c' % The MD5 Checksum of the message definition
        PropertyList = { 'Tau' } % List of non-constant message properties
        ROSPropertyList = { 'tau' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Tau
    end
    methods
        function set.Tau(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RBDLInverseDynamicsResponse', 'Tau');
            obj.Tau = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLInverseDynamicsResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLInverseDynamicsResponse(strObj);
        end
    end
end
