
classdef RBDLInverseKinimaticsResponse < ros.Message
    %RBDLInverseKinimaticsResponse MATLAB implementation of rbdl_server/RBDLInverseKinimaticsResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLInverseKinimaticsResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f3258c0e1786aef3f710d2b34dce99b7' % The MD5 Checksum of the message definition
        PropertyList = { 'QRes' 'Worked' } % List of non-constant message properties
        ROSPropertyList = { 'q_res' 'worked' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        QRes
        Worked
    end
    methods
        function set.QRes(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RBDLInverseKinimaticsResponse', 'QRes');
            obj.QRes = double(val);
        end
        function set.Worked(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RBDLInverseKinimaticsResponse', 'Worked');
            obj.Worked = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLInverseKinimaticsResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLInverseKinimaticsResponse(strObj);
        end
    end
end
