
classdef RBDLBodyNamesResponse < ros.Message
    %RBDLBodyNamesResponse MATLAB implementation of rbdl_server/RBDLBodyNamesResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLBodyNamesResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'dc7ae3609524b18034e49294a4ce670e' % The MD5 Checksum of the message definition
        PropertyList = { 'Names' } % List of non-constant message properties
        ROSPropertyList = { 'names' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Names
    end
    methods
        function set.Names(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RBDLBodyNamesResponse', 'Names');
            obj.Names = cell(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLBodyNamesResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLBodyNamesResponse(strObj);
        end
    end
end
