// Generated by gencpp from file rbdl_server/RBDLInverseDynamicsRequest.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLINVERSEDYNAMICSREQUEST_H
#define RBDL_SERVER_MESSAGE_RBDLINVERSEDYNAMICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLInverseDynamicsRequest_
{
  typedef RBDLInverseDynamicsRequest_<ContainerAllocator> Type;

  RBDLInverseDynamicsRequest_()
    : q()
    , qd()
    , qdd()  {
    }
  RBDLInverseDynamicsRequest_(const ContainerAllocator& _alloc)
    : q(_alloc)
    , qd(_alloc)
    , qdd(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_type;
  _q_type q;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _qd_type;
  _qd_type qd;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _qdd_type;
  _qdd_type qdd;





  typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLInverseDynamicsRequest_

typedef ::rbdl_server::RBDLInverseDynamicsRequest_<std::allocator<void> > RBDLInverseDynamicsRequest;

typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsRequest > RBDLInverseDynamicsRequestPtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsRequest const> RBDLInverseDynamicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q &&
    lhs.qd == rhs.qd &&
    lhs.qdd == rhs.qdd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8887e7f8d984bbbaee6fa405b1ec22de";
  }

  static const char* value(const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8887e7f8d984bbbaULL;
  static const uint64_t static_value2 = 0xee6fa405b1ec22deULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLInverseDynamicsRequest";
  }

  static const char* value(const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] q\n"
"float64[] qd\n"
"float64[] qdd\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
      stream.next(m.qd);
      stream.next(m.qdd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLInverseDynamicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLInverseDynamicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "qd[]" << std::endl;
    for (size_t i = 0; i < v.qd.size(); ++i)
    {
      s << indent << "  qd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.qd[i]);
    }
    s << indent << "qdd[]" << std::endl;
    for (size_t i = 0; i < v.qdd.size(); ++i)
    {
      s << indent << "  qdd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.qdd[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLINVERSEDYNAMICSREQUEST_H
