// Generated by gencpp from file rbdl_server/RBDLBodyNamesRequest.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLBODYNAMESREQUEST_H
#define RBDL_SERVER_MESSAGE_RBDLBODYNAMESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLBodyNamesRequest_
{
  typedef RBDLBodyNamesRequest_<ContainerAllocator> Type;

  RBDLBodyNamesRequest_()
    {
    }
  RBDLBodyNamesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLBodyNamesRequest_

typedef ::rbdl_server::RBDLBodyNamesRequest_<std::allocator<void> > RBDLBodyNamesRequest;

typedef boost::shared_ptr< ::rbdl_server::RBDLBodyNamesRequest > RBDLBodyNamesRequestPtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLBodyNamesRequest const> RBDLBodyNamesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLBodyNamesRequest";
  }

  static const char* value(const ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLBodyNamesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rbdl_server::RBDLBodyNamesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLBODYNAMESREQUEST_H
