// Generated by gencpp from file rbdl_server/RBDLModel.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLMODEL_H
#define RBDL_SERVER_MESSAGE_RBDLMODEL_H

#include <ros/service_traits.h>


#include <rbdl_server/RBDLModelRequest.h>
#include <rbdl_server/RBDLModelResponse.h>


namespace rbdl_server
{

struct RBDLModel
{

typedef RBDLModelRequest Request;
typedef RBDLModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RBDLModel
} // namespace rbdl_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbdl_server::RBDLModel > {
  static const char* value()
  {
    return "d092f66b4213534ea05b76cd5ee71314";
  }

  static const char* value(const ::rbdl_server::RBDLModel&) { return value(); }
};

template<>
struct DataType< ::rbdl_server::RBDLModel > {
  static const char* value()
  {
    return "rbdl_server/RBDLModel";
  }

  static const char* value(const ::rbdl_server::RBDLModel&) { return value(); }
};


// service_traits::MD5Sum< ::rbdl_server::RBDLModelRequest> should match
// service_traits::MD5Sum< ::rbdl_server::RBDLModel >
template<>
struct MD5Sum< ::rbdl_server::RBDLModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLModel >::value();
  }
  static const char* value(const ::rbdl_server::RBDLModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLModelRequest> should match
// service_traits::DataType< ::rbdl_server::RBDLModel >
template<>
struct DataType< ::rbdl_server::RBDLModelRequest>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLModel >::value();
  }
  static const char* value(const ::rbdl_server::RBDLModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbdl_server::RBDLModelResponse> should match
// service_traits::MD5Sum< ::rbdl_server::RBDLModel >
template<>
struct MD5Sum< ::rbdl_server::RBDLModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLModel >::value();
  }
  static const char* value(const ::rbdl_server::RBDLModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLModelResponse> should match
// service_traits::DataType< ::rbdl_server::RBDLModel >
template<>
struct DataType< ::rbdl_server::RBDLModelResponse>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLModel >::value();
  }
  static const char* value(const ::rbdl_server::RBDLModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLMODEL_H
