// Generated by gencpp from file rbdl_server/RBDLKinimaticsResponse.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLKINIMATICSRESPONSE_H
#define RBDL_SERVER_MESSAGE_RBDLKINIMATICSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLKinimaticsResponse_
{
  typedef RBDLKinimaticsResponse_<ContainerAllocator> Type;

  RBDLKinimaticsResponse_()
    : names()
    , points()  {
    }
  RBDLKinimaticsResponse_(const ContainerAllocator& _alloc)
    : names(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLKinimaticsResponse_

typedef ::rbdl_server::RBDLKinimaticsResponse_<std::allocator<void> > RBDLKinimaticsResponse;

typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsResponse > RBDLKinimaticsResponsePtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsResponse const> RBDLKinimaticsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.names == rhs.names &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e65d9ceb74470ff27829ed47650deb13";
  }

  static const char* value(const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe65d9ceb74470ff2ULL;
  static const uint64_t static_value2 = 0x7829ed47650deb13ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLKinimaticsResponse";
  }

  static const char* value(const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n"
"geometry_msgs/Point[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLKinimaticsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLKinimaticsResponse_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLKINIMATICSRESPONSE_H
