// Generated by gencpp from file rbdl_server/RBDLForwardDynamicsRequest.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICSREQUEST_H
#define RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLForwardDynamicsRequest_
{
  typedef RBDLForwardDynamicsRequest_<ContainerAllocator> Type;

  RBDLForwardDynamicsRequest_()
    : q()
    , qd()
    , tau()  {
    }
  RBDLForwardDynamicsRequest_(const ContainerAllocator& _alloc)
    : q(_alloc)
    , qd(_alloc)
    , tau(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_type;
  _q_type q;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _qd_type;
  _qd_type qd;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _tau_type;
  _tau_type tau;





  typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLForwardDynamicsRequest_

typedef ::rbdl_server::RBDLForwardDynamicsRequest_<std::allocator<void> > RBDLForwardDynamicsRequest;

typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsRequest > RBDLForwardDynamicsRequestPtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsRequest const> RBDLForwardDynamicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q &&
    lhs.qd == rhs.qd &&
    lhs.tau == rhs.tau;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65aaad731b9018a695899e0b9a800eeb";
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65aaad731b9018a6ULL;
  static const uint64_t static_value2 = 0x95899e0b9a800eebULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLForwardDynamicsRequest";
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] q\n"
"float64[] qd\n"
"float64[] tau\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
      stream.next(m.qd);
      stream.next(m.tau);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLForwardDynamicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLForwardDynamicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "qd[]" << std::endl;
    for (size_t i = 0; i < v.qd.size(); ++i)
    {
      s << indent << "  qd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.qd[i]);
    }
    s << indent << "tau[]" << std::endl;
    for (size_t i = 0; i < v.tau.size(); ++i)
    {
      s << indent << "  tau[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tau[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICSREQUEST_H
