// Generated by gencpp from file rbdl_server/RBDLInverseDynamicsResponse.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLINVERSEDYNAMICSRESPONSE_H
#define RBDL_SERVER_MESSAGE_RBDLINVERSEDYNAMICSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLInverseDynamicsResponse_
{
  typedef RBDLInverseDynamicsResponse_<ContainerAllocator> Type;

  RBDLInverseDynamicsResponse_()
    : tau()  {
    }
  RBDLInverseDynamicsResponse_(const ContainerAllocator& _alloc)
    : tau(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _tau_type;
  _tau_type tau;





  typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLInverseDynamicsResponse_

typedef ::rbdl_server::RBDLInverseDynamicsResponse_<std::allocator<void> > RBDLInverseDynamicsResponse;

typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsResponse > RBDLInverseDynamicsResponsePtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLInverseDynamicsResponse const> RBDLInverseDynamicsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tau == rhs.tau;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6488f72361a7c3710faf21208a8c781c";
  }

  static const char* value(const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6488f72361a7c371ULL;
  static const uint64_t static_value2 = 0x0faf21208a8c781cULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLInverseDynamicsResponse";
  }

  static const char* value(const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] tau\n"
"\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tau);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLInverseDynamicsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLInverseDynamicsResponse_<ContainerAllocator>& v)
  {
    s << indent << "tau[]" << std::endl;
    for (size_t i = 0; i < v.tau.size(); ++i)
    {
      s << indent << "  tau[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tau[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLINVERSEDYNAMICSRESPONSE_H
