// Generated by gencpp from file rbdl_server/RBDLKinimaticsRequest.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLKINIMATICSREQUEST_H
#define RBDL_SERVER_MESSAGE_RBDLKINIMATICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLKinimaticsRequest_
{
  typedef RBDLKinimaticsRequest_<ContainerAllocator> Type;

  RBDLKinimaticsRequest_()
    : q()  {
    }
  RBDLKinimaticsRequest_(const ContainerAllocator& _alloc)
    : q(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _q_type;
  _q_type q;





  typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLKinimaticsRequest_

typedef ::rbdl_server::RBDLKinimaticsRequest_<std::allocator<void> > RBDLKinimaticsRequest;

typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsRequest > RBDLKinimaticsRequestPtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLKinimaticsRequest const> RBDLKinimaticsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab94b9bcaaa12f74def43e4b33992df1";
  }

  static const char* value(const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab94b9bcaaa12f74ULL;
  static const uint64_t static_value2 = 0xdef43e4b33992df1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLKinimaticsRequest";
  }

  static const char* value(const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] q\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLKinimaticsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLKinimaticsRequest_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLKINIMATICSREQUEST_H
