// Generated by gencpp from file rbdl_server/RBDLForwardDynamicsResponse.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICSRESPONSE_H
#define RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLForwardDynamicsResponse_
{
  typedef RBDLForwardDynamicsResponse_<ContainerAllocator> Type;

  RBDLForwardDynamicsResponse_()
    : qdd()  {
    }
  RBDLForwardDynamicsResponse_(const ContainerAllocator& _alloc)
    : qdd(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _qdd_type;
  _qdd_type qdd;





  typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLForwardDynamicsResponse_

typedef ::rbdl_server::RBDLForwardDynamicsResponse_<std::allocator<void> > RBDLForwardDynamicsResponse;

typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsResponse > RBDLForwardDynamicsResponsePtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLForwardDynamicsResponse const> RBDLForwardDynamicsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.qdd == rhs.qdd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9f5346aad9a21a7c1a3fdc3006a6c17";
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9f5346aad9a21a7ULL;
  static const uint64_t static_value2 = 0xc1a3fdc3006a6c17ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLForwardDynamicsResponse";
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] qdd\n"
"\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qdd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLForwardDynamicsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLForwardDynamicsResponse_<ContainerAllocator>& v)
  {
    s << indent << "qdd[]" << std::endl;
    for (size_t i = 0; i < v.qdd.size(); ++i)
    {
      s << indent << "  qdd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.qdd[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICSRESPONSE_H
