// Generated by gencpp from file rbdl_server/RBDLModelResponse.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLMODELRESPONSE_H
#define RBDL_SERVER_MESSAGE_RBDLMODELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLModelResponse_
{
  typedef RBDLModelResponse_<ContainerAllocator> Type;

  RBDLModelResponse_()
    : good(false)  {
    }
  RBDLModelResponse_(const ContainerAllocator& _alloc)
    : good(false)  {
  (void)_alloc;
    }



   typedef uint8_t _good_type;
  _good_type good;





  typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLModelResponse_

typedef ::rbdl_server::RBDLModelResponse_<std::allocator<void> > RBDLModelResponse;

typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse > RBDLModelResponsePtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse const> RBDLModelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLModelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLModelResponse_<ContainerAllocator2> & rhs)
{
  return lhs.good == rhs.good;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator1> & lhs, const ::rbdl_server::RBDLModelResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rbdl_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420aeb7337f0734e9777121e7c6c96a3";
  }

  static const char* value(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420aeb7337f0734eULL;
  static const uint64_t static_value2 = 0x9777121e7c6c96a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLModelResponse";
  }

  static const char* value(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool good\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.good);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLModelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>& v)
  {
    s << indent << "good: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.good);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLMODELRESPONSE_H
