set(_CATKIN_CURRENT_PACKAGE "rbdl_server")
set(rbdl_server_VERSION "0.0.0")
set(rbdl_server_MAINTAINER "shreyas <shreyas@todo.todo>")
set(rbdl_server_PACKAGE_FORMAT "2")
set(rbdl_server_BUILD_DEPENDS "roscpp" "geometry_msgs" "message_generation" "tf" "rbdl_model")
set(rbdl_server_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "tf" "rbdl_model")
set(rbdl_server_BUILDTOOL_DEPENDS "catkin")
set(rbdl_server_BUILDTOOL_EXPORT_DEPENDS )
set(rbdl_server_EXEC_DEPENDS "roscpp" "geometry_msgs" "message_runtime" "tf" "rbdl_model")
set(rbdl_server_RUN_DEPENDS "roscpp" "geometry_msgs" "message_runtime" "tf" "rbdl_model")
set(rbdl_server_TEST_DEPENDS )
set(rbdl_server_DOC_DEPENDS )
set(rbdl_server_URL_WEBSITE "")
set(rbdl_server_URL_BUGTRACKER "")
set(rbdl_server_URL_REPOSITORY "")
set(rbdl_server_DEPRECATED "")