
classdef ControllerListResponse < ros.Message
    %ControllerListResponse MATLAB implementation of controller_modules/ControllerListResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'controller_modules/ControllerListResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8242783a458107f102bce0800c333f0a' % The MD5 Checksum of the message definition
        PropertyList = { 'Controllers' } % List of non-constant message properties
        ROSPropertyList = { 'controllers' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Controllers
    end
    methods
        function set.Controllers(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ControllerListResponse', 'Controllers');
            obj.Controllers = cell(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.controller_modules.ControllerListResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.controller_modules.ControllerListResponse(strObj);
        end
    end
end
