
classdef JointControlResponse < ros.Message
    %JointControlResponse MATLAB implementation of controller_modules/JointControlResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'controller_modules/JointControlResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2ec3ebfca49414b25763484f58b5180b' % The MD5 Checksum of the message definition
        PropertyList = { 'ControlOutput' } % List of non-constant message properties
        ROSPropertyList = { 'control_output' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.trajectory_msgs.JointTrajectoryPoint' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ControlOutput
    end
    methods
        function set.ControlOutput(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.trajectory_msgs.JointTrajectoryPoint'};
            validateattributes(val, validClasses, validAttributes, 'JointControlResponse', 'ControlOutput')
            obj.ControlOutput = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.controller_modules.JointControlResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.controller_modules.JointControlResponse(strObj);
        end
    end
end
