
classdef RBDLKinimaticsRequest < ros.Message
    %RBDLKinimaticsRequest MATLAB implementation of rbdl_server/RBDLKinimaticsRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLKinimaticsRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8c09c14f3d67b23dfb755e6efac36bcd' % The MD5 Checksum of the message definition
        PropertyList = { 'ModelName' 'Q' } % List of non-constant message properties
        ROSPropertyList = { 'model_name' 'q' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ModelName
        Q
    end
    methods
        function set.ModelName(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RBDLKinimaticsRequest', 'ModelName');
            obj.ModelName = char(val);
        end
        function set.Q(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RBDLKinimaticsRequest', 'Q');
            obj.Q = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLKinimaticsRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLKinimaticsRequest(strObj);
        end
    end
end
