
classdef RBDLForwardDynamicsResponse < ros.Message
    %RBDLForwardDynamicsResponse MATLAB implementation of rbdl_server/RBDLForwardDynamicsResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLForwardDynamicsResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f9f5346aad9a21a7c1a3fdc3006a6c17' % The MD5 Checksum of the message definition
        PropertyList = { 'Qdd' } % List of non-constant message properties
        ROSPropertyList = { 'qdd' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Qdd
    end
    methods
        function set.Qdd(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'RBDLForwardDynamicsResponse', 'Qdd');
            obj.Qdd = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLForwardDynamicsResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLForwardDynamicsResponse(strObj);
        end
    end
end
