
classdef RBDLJacobianResponse < ros.Message
    %RBDLJacobianResponse MATLAB implementation of rbdl_server/RBDLJacobianResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rbdl_server/RBDLJacobianResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2d411acbcc9bdcb049d050b7d07331de' % The MD5 Checksum of the message definition
        PropertyList = { 'Jacobian' } % List of non-constant message properties
        ROSPropertyList = { 'jacobian' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Float64MultiArray' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Jacobian
    end
    methods
        function set.Jacobian(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Float64MultiArray'};
            validateattributes(val, validClasses, validAttributes, 'RBDLJacobianResponse', 'Jacobian')
            obj.Jacobian = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rbdl_server.RBDLJacobianResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rbdl_server.RBDLJacobianResponse(strObj);
        end
    end
end
