; Auto-generated. Do not edit!


(cl:in-package rbdl_server-srv)


;//! \htmlinclude RBDLForwardDynamics-request.msg.html

(cl:defclass <RBDLForwardDynamics-request> (roslisp-msg-protocol:ros-message)
  ((q
    :reader q
    :initarg :q
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (qd
    :reader qd
    :initarg :qd
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (tau
    :reader tau
    :initarg :tau
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass RBDLForwardDynamics-request (<RBDLForwardDynamics-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RBDLForwardDynamics-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RBDLForwardDynamics-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rbdl_server-srv:<RBDLForwardDynamics-request> is deprecated: use rbdl_server-srv:RBDLForwardDynamics-request instead.")))

(cl:ensure-generic-function 'q-val :lambda-list '(m))
(cl:defmethod q-val ((m <RBDLForwardDynamics-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rbdl_server-srv:q-val is deprecated.  Use rbdl_server-srv:q instead.")
  (q m))

(cl:ensure-generic-function 'qd-val :lambda-list '(m))
(cl:defmethod qd-val ((m <RBDLForwardDynamics-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rbdl_server-srv:qd-val is deprecated.  Use rbdl_server-srv:qd instead.")
  (qd m))

(cl:ensure-generic-function 'tau-val :lambda-list '(m))
(cl:defmethod tau-val ((m <RBDLForwardDynamics-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rbdl_server-srv:tau-val is deprecated.  Use rbdl_server-srv:tau instead.")
  (tau m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RBDLForwardDynamics-request>) ostream)
  "Serializes a message object of type '<RBDLForwardDynamics-request>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'q))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'q))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'qd))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'qd))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'tau))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'tau))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RBDLForwardDynamics-request>) istream)
  "Deserializes a message object of type '<RBDLForwardDynamics-request>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'q) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'q)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'qd) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'qd)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'tau) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'tau)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RBDLForwardDynamics-request>)))
  "Returns string type for a service object of type '<RBDLForwardDynamics-request>"
  "rbdl_server/RBDLForwardDynamicsRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RBDLForwardDynamics-request)))
  "Returns string type for a service object of type 'RBDLForwardDynamics-request"
  "rbdl_server/RBDLForwardDynamicsRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RBDLForwardDynamics-request>)))
  "Returns md5sum for a message object of type '<RBDLForwardDynamics-request>"
  "2510e5eefce24dbe51d450b7f1432820")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RBDLForwardDynamics-request)))
  "Returns md5sum for a message object of type 'RBDLForwardDynamics-request"
  "2510e5eefce24dbe51d450b7f1432820")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RBDLForwardDynamics-request>)))
  "Returns full string definition for message of type '<RBDLForwardDynamics-request>"
  (cl:format cl:nil "float64[] q~%float64[] qd~%float64[] tau~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RBDLForwardDynamics-request)))
  "Returns full string definition for message of type 'RBDLForwardDynamics-request"
  (cl:format cl:nil "float64[] q~%float64[] qd~%float64[] tau~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RBDLForwardDynamics-request>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'q) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'qd) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'tau) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RBDLForwardDynamics-request>))
  "Converts a ROS message object to a list"
  (cl:list 'RBDLForwardDynamics-request
    (cl:cons ':q (q msg))
    (cl:cons ':qd (qd msg))
    (cl:cons ':tau (tau msg))
))
;//! \htmlinclude RBDLForwardDynamics-response.msg.html

(cl:defclass <RBDLForwardDynamics-response> (roslisp-msg-protocol:ros-message)
  ((qdd
    :reader qdd
    :initarg :qdd
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass RBDLForwardDynamics-response (<RBDLForwardDynamics-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RBDLForwardDynamics-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RBDLForwardDynamics-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rbdl_server-srv:<RBDLForwardDynamics-response> is deprecated: use rbdl_server-srv:RBDLForwardDynamics-response instead.")))

(cl:ensure-generic-function 'qdd-val :lambda-list '(m))
(cl:defmethod qdd-val ((m <RBDLForwardDynamics-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rbdl_server-srv:qdd-val is deprecated.  Use rbdl_server-srv:qdd instead.")
  (qdd m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RBDLForwardDynamics-response>) ostream)
  "Serializes a message object of type '<RBDLForwardDynamics-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'qdd))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'qdd))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RBDLForwardDynamics-response>) istream)
  "Deserializes a message object of type '<RBDLForwardDynamics-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'qdd) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'qdd)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RBDLForwardDynamics-response>)))
  "Returns string type for a service object of type '<RBDLForwardDynamics-response>"
  "rbdl_server/RBDLForwardDynamicsResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RBDLForwardDynamics-response)))
  "Returns string type for a service object of type 'RBDLForwardDynamics-response"
  "rbdl_server/RBDLForwardDynamicsResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RBDLForwardDynamics-response>)))
  "Returns md5sum for a message object of type '<RBDLForwardDynamics-response>"
  "2510e5eefce24dbe51d450b7f1432820")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RBDLForwardDynamics-response)))
  "Returns md5sum for a message object of type 'RBDLForwardDynamics-response"
  "2510e5eefce24dbe51d450b7f1432820")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RBDLForwardDynamics-response>)))
  "Returns full string definition for message of type '<RBDLForwardDynamics-response>"
  (cl:format cl:nil "float64[] qdd~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RBDLForwardDynamics-response)))
  "Returns full string definition for message of type 'RBDLForwardDynamics-response"
  (cl:format cl:nil "float64[] qdd~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RBDLForwardDynamics-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'qdd) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RBDLForwardDynamics-response>))
  "Converts a ROS message object to a list"
  (cl:list 'RBDLForwardDynamics-response
    (cl:cons ':qdd (qdd msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'RBDLForwardDynamics)))
  'RBDLForwardDynamics-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'RBDLForwardDynamics)))
  'RBDLForwardDynamics-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RBDLForwardDynamics)))
  "Returns string type for a service object of type '<RBDLForwardDynamics>"
  "rbdl_server/RBDLForwardDynamics")