set(_CATKIN_CURRENT_PACKAGE "rbdl_model_tests")
set(rbdl_model_tests_VERSION "0.0.0")
set(rbdl_model_tests_MAINTAINER "shreyas <shreyas@todo.todo>")
set(rbdl_model_tests_PACKAGE_FORMAT "2")
set(rbdl_model_tests_BUILD_DEPENDS "geometry_msgs" "message_generation" "tf" "rbdl_model" "std_msgs")
set(rbdl_model_tests_BUILD_EXPORT_DEPENDS "geometry_msgs" "tf" "rbdl_model" "rbdl_model" "std_msgs")
set(rbdl_model_tests_BUILDTOOL_DEPENDS "catkin")
set(rbdl_model_tests_BUILDTOOL_EXPORT_DEPENDS )
set(rbdl_model_tests_EXEC_DEPENDS "geometry_msgs" "tf" "message_runtime" "rbdl_model" "std_msgs")
set(rbdl_model_tests_RUN_DEPENDS "geometry_msgs" "tf" "message_runtime" "rbdl_model" "std_msgs")
set(rbdl_model_tests_TEST_DEPENDS )
set(rbdl_model_tests_DOC_DEPENDS )
set(rbdl_model_tests_URL_WEBSITE "")
set(rbdl_model_tests_URL_BUGTRACKER "")
set(rbdl_model_tests_URL_REPOSITORY "")
set(rbdl_model_tests_DEPRECATED "")