// Generated by gencpp from file rbdl_server/RBDLModelResponse.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLMODELRESPONSE_H
#define RBDL_SERVER_MESSAGE_RBDLMODELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbdl_server
{
template <class ContainerAllocator>
struct RBDLModelResponse_
{
  typedef RBDLModelResponse_<ContainerAllocator> Type;

  RBDLModelResponse_()
    : good(false)  {
    }
  RBDLModelResponse_(const ContainerAllocator& _alloc)
    : good(false)  {
  (void)_alloc;
    }



   typedef uint8_t _good_type;
  _good_type good;





  typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RBDLModelResponse_

typedef ::rbdl_server::RBDLModelResponse_<std::allocator<void> > RBDLModelResponse;

typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse > RBDLModelResponsePtr;
typedef boost::shared_ptr< ::rbdl_server::RBDLModelResponse const> RBDLModelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbdl_server::RBDLModelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rbdl_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420aeb7337f0734e9777121e7c6c96a3";
  }

  static const char* value(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420aeb7337f0734eULL;
  static const uint64_t static_value2 = 0x9777121e7c6c96a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbdl_server/RBDLModelResponse";
  }

  static const char* value(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool good\n"
;
  }

  static const char* value(const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.good);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RBDLModelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbdl_server::RBDLModelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbdl_server::RBDLModelResponse_<ContainerAllocator>& v)
  {
    s << indent << "good: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.good);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLMODELRESPONSE_H
