// Generated by gencpp from file rbdl_server/RBDLForwardDynamics.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICS_H
#define RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICS_H

#include <ros/service_traits.h>


#include <rbdl_server/RBDLForwardDynamicsRequest.h>
#include <rbdl_server/RBDLForwardDynamicsResponse.h>


namespace rbdl_server
{

struct RBDLForwardDynamics
{

typedef RBDLForwardDynamicsRequest Request;
typedef RBDLForwardDynamicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RBDLForwardDynamics
} // namespace rbdl_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbdl_server::RBDLForwardDynamics > {
  static const char* value()
  {
    return "859d20e3a81b731177dea2b878bac34b";
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamics&) { return value(); }
};

template<>
struct DataType< ::rbdl_server::RBDLForwardDynamics > {
  static const char* value()
  {
    return "rbdl_server/RBDLForwardDynamics";
  }

  static const char* value(const ::rbdl_server::RBDLForwardDynamics&) { return value(); }
};


// service_traits::MD5Sum< ::rbdl_server::RBDLForwardDynamicsRequest> should match 
// service_traits::MD5Sum< ::rbdl_server::RBDLForwardDynamics > 
template<>
struct MD5Sum< ::rbdl_server::RBDLForwardDynamicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLForwardDynamics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLForwardDynamicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLForwardDynamicsRequest> should match 
// service_traits::DataType< ::rbdl_server::RBDLForwardDynamics > 
template<>
struct DataType< ::rbdl_server::RBDLForwardDynamicsRequest>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLForwardDynamics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLForwardDynamicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbdl_server::RBDLForwardDynamicsResponse> should match 
// service_traits::MD5Sum< ::rbdl_server::RBDLForwardDynamics > 
template<>
struct MD5Sum< ::rbdl_server::RBDLForwardDynamicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLForwardDynamics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLForwardDynamicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLForwardDynamicsResponse> should match 
// service_traits::DataType< ::rbdl_server::RBDLForwardDynamics > 
template<>
struct DataType< ::rbdl_server::RBDLForwardDynamicsResponse>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLForwardDynamics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLForwardDynamicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLFORWARDDYNAMICS_H
