set(_CATKIN_CURRENT_PACKAGE "rbdl_model")
set(rbdl_model_VERSION "0.0.0")
set(rbdl_model_MAINTAINER "shreyas <shreyas@todo.todo>")
set(rbdl_model_PACKAGE_FORMAT "2")
set(rbdl_model_BUILD_DEPENDS )
set(rbdl_model_BUILD_EXPORT_DEPENDS )
set(rbdl_model_BUILDTOOL_DEPENDS "catkin")
set(rbdl_model_BUILDTOOL_EXPORT_DEPENDS )
set(rbdl_model_EXEC_DEPENDS )
set(rbdl_model_RUN_DEPENDS )
set(rbdl_model_TEST_DEPENDS )
set(rbdl_model_DOC_DEPENDS )
set(rbdl_model_URL_WEBSITE "")
set(rbdl_model_URL_BUGTRACKER "")
set(rbdl_model_URL_REPOSITORY "")
set(rbdl_model_DEPRECATED "")