// Generated by gencpp from file rbdl_server/RBDLJacobian.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLJACOBIAN_H
#define RBDL_SERVER_MESSAGE_RBDLJACOBIAN_H

#include <ros/service_traits.h>


#include <rbdl_server/RBDLJacobianRequest.h>
#include <rbdl_server/RBDLJacobianResponse.h>


namespace rbdl_server
{

struct RBDLJacobian
{

typedef RBDLJacobianRequest Request;
typedef RBDLJacobianResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RBDLJacobian
} // namespace rbdl_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbdl_server::RBDLJacobian > {
  static const char* value()
  {
    return "3a0f5b9cd0e0af3b589fdefd8d1ffd2c";
  }

  static const char* value(const ::rbdl_server::RBDLJacobian&) { return value(); }
};

template<>
struct DataType< ::rbdl_server::RBDLJacobian > {
  static const char* value()
  {
    return "rbdl_server/RBDLJacobian";
  }

  static const char* value(const ::rbdl_server::RBDLJacobian&) { return value(); }
};


// service_traits::MD5Sum< ::rbdl_server::RBDLJacobianRequest> should match 
// service_traits::MD5Sum< ::rbdl_server::RBDLJacobian > 
template<>
struct MD5Sum< ::rbdl_server::RBDLJacobianRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLJacobian >::value();
  }
  static const char* value(const ::rbdl_server::RBDLJacobianRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLJacobianRequest> should match 
// service_traits::DataType< ::rbdl_server::RBDLJacobian > 
template<>
struct DataType< ::rbdl_server::RBDLJacobianRequest>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLJacobian >::value();
  }
  static const char* value(const ::rbdl_server::RBDLJacobianRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbdl_server::RBDLJacobianResponse> should match 
// service_traits::MD5Sum< ::rbdl_server::RBDLJacobian > 
template<>
struct MD5Sum< ::rbdl_server::RBDLJacobianResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLJacobian >::value();
  }
  static const char* value(const ::rbdl_server::RBDLJacobianResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLJacobianResponse> should match 
// service_traits::DataType< ::rbdl_server::RBDLJacobian > 
template<>
struct DataType< ::rbdl_server::RBDLJacobianResponse>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLJacobian >::value();
  }
  static const char* value(const ::rbdl_server::RBDLJacobianResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLJACOBIAN_H
