// Generated by gencpp from file rbdl_server/RBDLKinimatics.msg
// DO NOT EDIT!


#ifndef RBDL_SERVER_MESSAGE_RBDLKINIMATICS_H
#define RBDL_SERVER_MESSAGE_RBDLKINIMATICS_H

#include <ros/service_traits.h>


#include <rbdl_server/RBDLKinimaticsRequest.h>
#include <rbdl_server/RBDLKinimaticsResponse.h>


namespace rbdl_server
{

struct RBDLKinimatics
{

typedef RBDLKinimaticsRequest Request;
typedef RBDLKinimaticsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RBDLKinimatics
} // namespace rbdl_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbdl_server::RBDLKinimatics > {
  static const char* value()
  {
    return "98ce653e1f60d79321ce1586e1f7fc70";
  }

  static const char* value(const ::rbdl_server::RBDLKinimatics&) { return value(); }
};

template<>
struct DataType< ::rbdl_server::RBDLKinimatics > {
  static const char* value()
  {
    return "rbdl_server/RBDLKinimatics";
  }

  static const char* value(const ::rbdl_server::RBDLKinimatics&) { return value(); }
};


// service_traits::MD5Sum< ::rbdl_server::RBDLKinimaticsRequest> should match 
// service_traits::MD5Sum< ::rbdl_server::RBDLKinimatics > 
template<>
struct MD5Sum< ::rbdl_server::RBDLKinimaticsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLKinimatics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLKinimaticsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLKinimaticsRequest> should match 
// service_traits::DataType< ::rbdl_server::RBDLKinimatics > 
template<>
struct DataType< ::rbdl_server::RBDLKinimaticsRequest>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLKinimatics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLKinimaticsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbdl_server::RBDLKinimaticsResponse> should match 
// service_traits::MD5Sum< ::rbdl_server::RBDLKinimatics > 
template<>
struct MD5Sum< ::rbdl_server::RBDLKinimaticsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbdl_server::RBDLKinimatics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLKinimaticsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbdl_server::RBDLKinimaticsResponse> should match 
// service_traits::DataType< ::rbdl_server::RBDLKinimatics > 
template<>
struct DataType< ::rbdl_server::RBDLKinimaticsResponse>
{
  static const char* value()
  {
    return DataType< ::rbdl_server::RBDLKinimatics >::value();
  }
  static const char* value(const ::rbdl_server::RBDLKinimaticsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBDL_SERVER_MESSAGE_RBDLKINIMATICS_H
