set(_CATKIN_CURRENT_PACKAGE "controller_modules")
set(controller_modules_VERSION "0.0.0")
set(controller_modules_MAINTAINER "shreyas <shreyas@todo.todo>")
set(controller_modules_PACKAGE_FORMAT "2")
set(controller_modules_BUILD_DEPENDS "geometry_msgs" "message_generation" "tf" "trajectory_msgs")
set(controller_modules_BUILD_EXPORT_DEPENDS "geometry_msgs" "geometry_msgs" "trajectory_msgs")
set(controller_modules_BUILDTOOL_DEPENDS "catkin")
set(controller_modules_BUILDTOOL_EXPORT_DEPENDS )
set(controller_modules_EXEC_DEPENDS "geometry_msgs" "tf" "trajectory_msgs")
set(controller_modules_RUN_DEPENDS "geometry_msgs" "tf" "trajectory_msgs")
set(controller_modules_TEST_DEPENDS )
set(controller_modules_DOC_DEPENDS )
set(controller_modules_URL_WEBSITE "")
set(controller_modules_URL_BUGTRACKER "")
set(controller_modules_URL_REPOSITORY "")
set(controller_modules_DEPRECATED "")