// Generated by gencpp from file controller_modules/JointControl.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MODULES_MESSAGE_JOINTCONTROL_H
#define CONTROLLER_MODULES_MESSAGE_JOINTCONTROL_H

#include <ros/service_traits.h>


#include <controller_modules/JointControlRequest.h>
#include <controller_modules/JointControlResponse.h>


namespace controller_modules
{

struct JointControl
{

typedef JointControlRequest Request;
typedef JointControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointControl
} // namespace controller_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller_modules::JointControl > {
  static const char* value()
  {
    return "48f8bb00f33b7039bd35678b2c6204e5";
  }

  static const char* value(const ::controller_modules::JointControl&) { return value(); }
};

template<>
struct DataType< ::controller_modules::JointControl > {
  static const char* value()
  {
    return "controller_modules/JointControl";
  }

  static const char* value(const ::controller_modules::JointControl&) { return value(); }
};


// service_traits::MD5Sum< ::controller_modules::JointControlRequest> should match
// service_traits::MD5Sum< ::controller_modules::JointControl >
template<>
struct MD5Sum< ::controller_modules::JointControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller_modules::JointControl >::value();
  }
  static const char* value(const ::controller_modules::JointControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_modules::JointControlRequest> should match
// service_traits::DataType< ::controller_modules::JointControl >
template<>
struct DataType< ::controller_modules::JointControlRequest>
{
  static const char* value()
  {
    return DataType< ::controller_modules::JointControl >::value();
  }
  static const char* value(const ::controller_modules::JointControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller_modules::JointControlResponse> should match
// service_traits::MD5Sum< ::controller_modules::JointControl >
template<>
struct MD5Sum< ::controller_modules::JointControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller_modules::JointControl >::value();
  }
  static const char* value(const ::controller_modules::JointControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller_modules::JointControlResponse> should match
// service_traits::DataType< ::controller_modules::JointControl >
template<>
struct DataType< ::controller_modules::JointControlResponse>
{
  static const char* value()
  {
    return DataType< ::controller_modules::JointControl >::value();
  }
  static const char* value(const ::controller_modules::JointControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MODULES_MESSAGE_JOINTCONTROL_H
